---
trigger: 
  - master

pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: golang-template
    type: github
    name: opstree/azure-devops-template
    endpoint: OT-CONTAINER-KIT

extends:
  template: golang-ci.yaml@golang-template
  parameters:
    ApplicationName: k8s-vault-webhook
    QuayImageName: opstree/k8s-vault-webhook
    GithubImageName: ot-container-kit/k8s-vault-webhook/k8s-vault-webhook
    BuildDocs: false
